//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 

namespace XMLTransformer
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class MessageStack
    {

        private object itemField;

        private PriorityType[] prioritiesField;

        private MessageStackFilter filterField;

        private MessageType[] messagesField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Origin", typeof(OriginType))]
        [System.Xml.Serialization.XmlElementAttribute("Origins", typeof(MessageStackOrigins))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Priority", IsNullable = false)]
        public PriorityType[] Priorities
        {
            get
            {
                return this.prioritiesField;
            }
            set
            {
                this.prioritiesField = value;
            }
        }

        /// <remarks/>
        public MessageStackFilter Filter
        {
            get
            {
                return this.filterField;
            }
            set
            {
                this.filterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable = false)]
        public MessageType[] Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OriginType
    {

        private System.DateTime timeStampField;

        private string originDescriptionField;

        private OriginTypeModule moduleField;

        private OriginTypeMachine machineField;

        /// <remarks/>
        public System.DateTime TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }

        /// <remarks/>
        public string OriginDescription
        {
            get
            {
                return this.originDescriptionField;
            }
            set
            {
                this.originDescriptionField = value;
            }
        }

        /// <remarks/>
        public OriginTypeModule Module
        {
            get
            {
                return this.moduleField;
            }
            set
            {
                this.moduleField = value;
            }
        }

        /// <remarks/>
        public OriginTypeMachine Machine
        {
            get
            {
                return this.machineField;
            }
            set
            {
                this.machineField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OriginTypeModule
    {

        private string identificationNumberField;

        private string identificationIndexField;

        private string serialNumberField;

        /// <remarks/>
        public string IdentificationNumber
        {
            get
            {
                return this.identificationNumberField;
            }
            set
            {
                this.identificationNumberField = value;
            }
        }

        /// <remarks/>
        public string IdentificationIndex
        {
            get
            {
                return this.identificationIndexField;
            }
            set
            {
                this.identificationIndexField = value;
            }
        }

        /// <remarks/>
        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StackedMessageType
    {

        private uint codeField;

        private AdditionalInfosType additionalInfosField;

        private GroupingType groupingField;

        private PriorityName priorityField;

        private bool deactiveField;

        private bool firstSinceStartupField;

        private bool serviceAcknowledgedField;

        private bool userAcknowledgedField;

        public StackedMessageType()
        {
            this.deactiveField = false;
            this.firstSinceStartupField = false;
            this.serviceAcknowledgedField = false;
            this.userAcknowledgedField = false;
        }

        /// <remarks/>
        public uint Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public AdditionalInfosType AdditionalInfos
        {
            get
            {
                return this.additionalInfosField;
            }
            set
            {
                this.additionalInfosField = value;
            }
        }

        /// <remarks/>
        public GroupingType Grouping
        {
            get
            {
                return this.groupingField;
            }
            set
            {
                this.groupingField = value;
            }
        }

        /// <remarks/>
        public PriorityName Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deactive
        {
            get
            {
                return this.deactiveField;
            }
            set
            {
                this.deactiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool FirstSinceStartup
        {
            get
            {
                return this.firstSinceStartupField;
            }
            set
            {
                this.firstSinceStartupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ServiceAcknowledged
        {
            get
            {
                return this.serviceAcknowledgedField;
            }
            set
            {
                this.serviceAcknowledgedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UserAcknowledged
        {
            get
            {
                return this.userAcknowledgedField;
            }
            set
            {
                this.userAcknowledgedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdditionalInfosType
    {

        private AdditionalInfosTypeAdditionalInfo[] additionalInfoField;

        private AdditionalComplex[] additionalComplexField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalInfo")]
        public AdditionalInfosTypeAdditionalInfo[] AdditionalInfo
        {
            get
            {
                return this.additionalInfoField;
            }
            set
            {
                this.additionalInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalComplex")]
        public AdditionalComplex[] AdditionalComplex
        {
            get
            {
                return this.additionalComplexField;
            }
            set
            {
                this.additionalComplexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AdditionalInfosTypeAdditionalInfo
    {

        private string identityField;

        private string unitField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdditionalComplex
    {

        private AdditionalComplexValue[] valueField;

        private AdditionalComplex[] additionalComplex1Field;

        private string identityField;

        private string unitField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public AdditionalComplexValue[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalComplex")]
        public AdditionalComplex[] AdditionalComplex1
        {
            get
            {
                return this.additionalComplex1Field;
            }
            set
            {
                this.additionalComplex1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AdditionalComplexValue
    {

        private string identityField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupingType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicat", typeof(GroupingTypeApplicat))]
        [System.Xml.Serialization.XmlElementAttribute("can", typeof(GroupingTypeCan))]
        [System.Xml.Serialization.XmlElementAttribute("inner", typeof(GroupingTypeInner))]
        [System.Xml.Serialization.XmlElementAttribute("j1939", typeof(GroupingTypeJ1939))]
        [System.Xml.Serialization.XmlElementAttribute("language", typeof(GroupingTypeLanguage))]
        [System.Xml.Serialization.XmlElementAttribute("lib", typeof(GroupingTypeLib))]
        [System.Xml.Serialization.XmlElementAttribute("lidat", typeof(GroupingTypeLidat))]
        [System.Xml.Serialization.XmlElementAttribute("null", typeof(GroupingTypeNull))]
        [System.Xml.Serialization.XmlElementAttribute("os", typeof(GroupingTypeOS))]
        [System.Xml.Serialization.XmlElementAttribute("outer", typeof(GroupingTypeOuter))]
        [System.Xml.Serialization.XmlElementAttribute("smallsystem", typeof(GroupingTypeSmallsystem))]
        [System.Xml.Serialization.XmlElementAttribute("tools", typeof(GroupingTypeTools))]
        [System.Xml.Serialization.XmlElementAttribute("undefined", typeof(GroupingTypeUndefined))]
        [System.Xml.Serialization.XmlElementAttribute("user", typeof(GroupingTypeUser))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeApplicat
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        sensor,

        /// <remarks/>
        actor,

        /// <remarks/>
        safety,

        /// <remarks/>
        drive,

        /// <remarks/>
        machine,

        /// <remarks/>
        engine,

        /// <remarks/>
        service,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeCan
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        system,

        /// <remarks/>
        application,

        /// <remarks/>
        boot,

        /// <remarks/>
        os,

        /// <remarks/>
        can,

        /// <remarks/>
        drivers,

        /// <remarks/>
        syscheck,

        /// <remarks/>
        utilities,

        /// <remarks/>
        recorder,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeInner
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        boot,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeJ1939
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        sensor,

        /// <remarks/>
        actor,

        /// <remarks/>
        safety,

        /// <remarks/>
        drive,

        /// <remarks/>
        machine,

        /// <remarks/>
        engine,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeLanguage
    {

        /// <remarks/>
        unit,

        /// <remarks/>
        pdr_tag,

        /// <remarks/>
        pdr_caption,

        /// <remarks/>
        screen,

        /// <remarks/>
        logger,

        /// <remarks/>
        pdeserv,

        /// <remarks/>
        pde,

        /// <remarks/>
        pde_graph,

        /// <remarks/>
        pdecnf_mode,

        /// <remarks/>
        pdecnf_data,

        /// <remarks/>
        pdecnf_data_short,

        /// <remarks/>
        pdecnf_input,

        /// <remarks/>
        pdecnf_head,

        /// <remarks/>
        pdecnf_mode_cons,

        /// <remarks/>
        pdecnf_input_cons,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeLib
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        slib,

        /// <remarks/>
        lwnlib,

        /// <remarks/>
        lml,

        /// <remarks/>
        geo,

        /// <remarks/>
        cycop,

        /// <remarks/>
        pde,

        /// <remarks/>
        control,

        /// <remarks/>
        j1939,

        /// <remarks/>
        security,

        /// <remarks/>
        uds_lib,

        /// <remarks/>
        ahc,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeLidat
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        value,

        /// <remarks/>
        sum,

        /// <remarks/>
        @event,

        /// <remarks/>
        communication,

        /// <remarks/>
        complex,

        /// <remarks/>
        script,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeNull
    {

        /// <remarks/>
        @null,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeOS
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        vxworks,

        /// <remarks/>
        win32,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeOuter
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        boot,

        /// <remarks/>
        can,

        /// <remarks/>
        syscheck,

        /// <remarks/>
        com,

        /// <remarks/>
        recorder,

        /// <remarks/>
        message,

        /// <remarks/>
        graphic,

        /// <remarks/>
        security,

        /// <remarks/>
        exception,

        /// <remarks/>
        rts,

        /// <remarks/>
        utilities,

        /// <remarks/>
        international,

        /// <remarks/>
        drivers,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeSmallsystem
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        uec3,

        /// <remarks/>
        master3event,

        /// <remarks/>
        miningexcavator,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("bst-bbt")]
        bstbbt,

        /// <remarks/>
        lidec,

        /// <remarks/>
        peripheral,

        /// <remarks/>
        dc4,

        /// <remarks/>
        dc5,

        /// <remarks/>
        lidec2,

        /// <remarks/>
        liab,

        /// <remarks/>
        frequencyconverter,

        /// <remarks/>
        energystorage,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeTools
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        communication,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeUndefined
    {

        /// <remarks/>
        undefined,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum GroupingTypeUser
    {

        /// <remarks/>
        undefined,

        /// <remarks/>
        lhm,

        /// <remarks/>
        hs,

        /// <remarks/>
        maritime,

        /// <remarks/>
        lrs,

        /// <remarks/>
        towercrane_error,

        /// <remarks/>
        towercrane_warning,

        /// <remarks/>
        towercrane_message,

        /// <remarks/>
        towercrane_status,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum PriorityName
    {

        /// <remarks/>
        fatal,

        /// <remarks/>
        alert,

        /// <remarks/>
        critical,

        /// <remarks/>
        system,

        /// <remarks/>
        error,

        /// <remarks/>
        warning,

        /// <remarks/>
        notice,

        /// <remarks/>
        info,

        /// <remarks/>
        debug,

        /// <remarks/>
        unaware,

        /// <remarks/>
        undefined,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageType
    {

        private uint codeField;

        private AdditionalInfosType additionalInfosField;

        private TimeStampType timeStampField;

        private TimeStampType timeStampLastOccurenceField;

        private string numberOfOccurencesField;

        private GroupingType groupingField;

        private PriorityName priorityField;

        private uint stackEntryIndexField;

        private bool stackEntryIndexFieldSpecified;

        private MessageTypeText[] textField;

        private StackedMessageType[] stackedMessagesField;

        private string originField;

        private string controlSystemPathField;

        private bool deactiveField;

        private bool firstSinceStartupField;

        private bool serviceAcknowledgedField;

        private bool userAcknowledgedField;

        public MessageType()
        {
            this.deactiveField = false;
            this.firstSinceStartupField = false;
            this.serviceAcknowledgedField = false;
            this.userAcknowledgedField = false;
        }

        /// <remarks/>
        public uint Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public AdditionalInfosType AdditionalInfos
        {
            get
            {
                return this.additionalInfosField;
            }
            set
            {
                this.additionalInfosField = value;
            }
        }

        /// <remarks/>
        public TimeStampType TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }

        /// <remarks/>
        public TimeStampType TimeStampLastOccurence
        {
            get
            {
                return this.timeStampLastOccurenceField;
            }
            set
            {
                this.timeStampLastOccurenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string NumberOfOccurences
        {
            get
            {
                return this.numberOfOccurencesField;
            }
            set
            {
                this.numberOfOccurencesField = value;
            }
        }

        /// <remarks/>
        public GroupingType Grouping
        {
            get
            {
                return this.groupingField;
            }
            set
            {
                this.groupingField = value;
            }
        }

        /// <remarks/>
        public PriorityName Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        public uint StackEntryIndex
        {
            get
            {
                return this.stackEntryIndexField;
            }
            set
            {
                this.stackEntryIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StackEntryIndexSpecified
        {
            get
            {
                return this.stackEntryIndexFieldSpecified;
            }
            set
            {
                this.stackEntryIndexFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public MessageTypeText[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StackedMessage", IsNullable = false)]
        public StackedMessageType[] StackedMessages
        {
            get
            {
                return this.stackedMessagesField;
            }
            set
            {
                this.stackedMessagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }

        /// <remarks/>
        public string ControlSystemPath
        {
            get
            {
                return this.controlSystemPathField;
            }
            set
            {
                this.controlSystemPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deactive
        {
            get
            {
                return this.deactiveField;
            }
            set
            {
                this.deactiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool FirstSinceStartup
        {
            get
            {
                return this.firstSinceStartupField;
            }
            set
            {
                this.firstSinceStartupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ServiceAcknowledged
        {
            get
            {
                return this.serviceAcknowledgedField;
            }
            set
            {
                this.serviceAcknowledgedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UserAcknowledged
        {
            get
            {
                return this.userAcknowledgedField;
            }
            set
            {
                this.userAcknowledgedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimeStampType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AbsoluteTime", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("OperatingHours", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MessageTypeText
    {

        private string languageField;

        private string descriptiveField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Descriptive
        {
            get
            {
                return this.descriptiveField;
            }
            set
            {
                this.descriptiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilterSetType
    {

        private bool filterSetActiveField;

        private string nameField;

        private string codeField;

        private TimeStampType timeStampBeginField;

        private TimeStampType timeStampEndField;

        private TimeStampType timeStampLastOccurenceBeginField;

        private TimeStampType timeStampLastOccurenceEndField;

        private string numberOfOccurencesBeginField;

        private string numberOfOccurencesEndField;

        private GroupingType groupingField;

        private PriorityName priorityLowField;

        private bool priorityLowFieldSpecified;

        private PriorityName priorityHighField;

        private bool priorityHighFieldSpecified;

        private bool deactiveField;

        private bool deactiveFieldSpecified;

        private bool firstSinceStartupField;

        private bool firstSinceStartupFieldSpecified;

        private bool serviceAcknowledgedField;

        private bool serviceAcknowledgedFieldSpecified;

        private bool userAcknowledgedField;

        private bool userAcknowledgedFieldSpecified;

        private uint stackEntryIndexRangeBeginField;

        private bool stackEntryIndexRangeBeginFieldSpecified;

        private uint stackEntryIndexRangeEndField;

        private bool stackEntryIndexRangeEndFieldSpecified;

        private string additionalInfoField;

        private string textField;

        /// <remarks/>
        public bool FilterSetActive
        {
            get
            {
                return this.filterSetActiveField;
            }
            set
            {
                this.filterSetActiveField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public TimeStampType TimeStampBegin
        {
            get
            {
                return this.timeStampBeginField;
            }
            set
            {
                this.timeStampBeginField = value;
            }
        }

        /// <remarks/>
        public TimeStampType TimeStampEnd
        {
            get
            {
                return this.timeStampEndField;
            }
            set
            {
                this.timeStampEndField = value;
            }
        }

        /// <remarks/>
        public TimeStampType TimeStampLastOccurenceBegin
        {
            get
            {
                return this.timeStampLastOccurenceBeginField;
            }
            set
            {
                this.timeStampLastOccurenceBeginField = value;
            }
        }

        /// <remarks/>
        public TimeStampType TimeStampLastOccurenceEnd
        {
            get
            {
                return this.timeStampLastOccurenceEndField;
            }
            set
            {
                this.timeStampLastOccurenceEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string NumberOfOccurencesBegin
        {
            get
            {
                return this.numberOfOccurencesBeginField;
            }
            set
            {
                this.numberOfOccurencesBeginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string NumberOfOccurencesEnd
        {
            get
            {
                return this.numberOfOccurencesEndField;
            }
            set
            {
                this.numberOfOccurencesEndField = value;
            }
        }

        /// <remarks/>
        public GroupingType Grouping
        {
            get
            {
                return this.groupingField;
            }
            set
            {
                this.groupingField = value;
            }
        }

        /// <remarks/>
        public PriorityName PriorityLow
        {
            get
            {
                return this.priorityLowField;
            }
            set
            {
                this.priorityLowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriorityLowSpecified
        {
            get
            {
                return this.priorityLowFieldSpecified;
            }
            set
            {
                this.priorityLowFieldSpecified = value;
            }
        }

        /// <remarks/>
        public PriorityName PriorityHigh
        {
            get
            {
                return this.priorityHighField;
            }
            set
            {
                this.priorityHighField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriorityHighSpecified
        {
            get
            {
                return this.priorityHighFieldSpecified;
            }
            set
            {
                this.priorityHighFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool Deactive
        {
            get
            {
                return this.deactiveField;
            }
            set
            {
                this.deactiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeactiveSpecified
        {
            get
            {
                return this.deactiveFieldSpecified;
            }
            set
            {
                this.deactiveFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool FirstSinceStartup
        {
            get
            {
                return this.firstSinceStartupField;
            }
            set
            {
                this.firstSinceStartupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstSinceStartupSpecified
        {
            get
            {
                return this.firstSinceStartupFieldSpecified;
            }
            set
            {
                this.firstSinceStartupFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool ServiceAcknowledged
        {
            get
            {
                return this.serviceAcknowledgedField;
            }
            set
            {
                this.serviceAcknowledgedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceAcknowledgedSpecified
        {
            get
            {
                return this.serviceAcknowledgedFieldSpecified;
            }
            set
            {
                this.serviceAcknowledgedFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool UserAcknowledged
        {
            get
            {
                return this.userAcknowledgedField;
            }
            set
            {
                this.userAcknowledgedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserAcknowledgedSpecified
        {
            get
            {
                return this.userAcknowledgedFieldSpecified;
            }
            set
            {
                this.userAcknowledgedFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint StackEntryIndexRangeBegin
        {
            get
            {
                return this.stackEntryIndexRangeBeginField;
            }
            set
            {
                this.stackEntryIndexRangeBeginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StackEntryIndexRangeBeginSpecified
        {
            get
            {
                return this.stackEntryIndexRangeBeginFieldSpecified;
            }
            set
            {
                this.stackEntryIndexRangeBeginFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint StackEntryIndexRangeEnd
        {
            get
            {
                return this.stackEntryIndexRangeEndField;
            }
            set
            {
                this.stackEntryIndexRangeEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StackEntryIndexRangeEndSpecified
        {
            get
            {
                return this.stackEntryIndexRangeEndFieldSpecified;
            }
            set
            {
                this.stackEntryIndexRangeEndFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string AdditionalInfo
        {
            get
            {
                return this.additionalInfoField;
            }
            set
            {
                this.additionalInfoField = value;
            }
        }

        /// <remarks/>
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PriorityType
    {

        private PriorityName priorityNameField;

        private string levelField;

        public PriorityType()
        {
            this.levelField = "0";
        }

        /// <remarks/>
        public PriorityName PriorityName
        {
            get
            {
                return this.priorityNameField;
            }
            set
            {
                this.priorityNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OriginTypeMachine
    {

        private string machineSerialNumberField;

        private string uniqueIDField;

        private string liuidField;

        /// <remarks/>
        public string MachineSerialNumber
        {
            get
            {
                return this.machineSerialNumberField;
            }
            set
            {
                this.machineSerialNumberField = value;
            }
        }

        /// <remarks/>
        public string UniqueID
        {
            get
            {
                return this.uniqueIDField;
            }
            set
            {
                this.uniqueIDField = value;
            }
        }

        /// <remarks/>
        public string Liuid
        {
            get
            {
                return this.liuidField;
            }
            set
            {
                this.liuidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MessageStackOrigins
    {

        private MessageStackOriginsOrigin[] originField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Origin")]
        public MessageStackOriginsOrigin[] Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MessageStackOriginsOrigin : OriginType
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MessageStackFilter
    {

        private bool inclusionField;

        private bool currentActiveField;

        private bool currentActiveFieldSpecified;

        private FilterSetType[] filterSetField;

        /// <remarks/>
        public bool Inclusion
        {
            get
            {
                return this.inclusionField;
            }
            set
            {
                this.inclusionField = value;
            }
        }

        /// <remarks/>
        public bool CurrentActive
        {
            get
            {
                return this.currentActiveField;
            }
            set
            {
                this.currentActiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrentActiveSpecified
        {
            get
            {
                return this.currentActiveFieldSpecified;
            }
            set
            {
                this.currentActiveFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FilterSet")]
        public FilterSetType[] FilterSet
        {
            get
            {
                return this.filterSetField;
            }
            set
            {
                this.filterSetField = value;
            }
        }
    }
}